version: '3.7'
services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DOCKER_DATA_PATH}/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ${DOCKER_DATA_PATH}/redis:/data
  server:
    build: ./server
    restart: always
    depends_on:
      - database
      - redis
  web:
    build: ./web
    restart: always
    depends_on:
      - server
