version: '3.7'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    volumes:
      - ./server/src:/usr/src/app/server_dev/src
    command: ['./wait-for-it.sh', 'database:5432', '--', 'yarn', 'dev']
  web:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    expose:
      - ${WEB_PORT}
    volumes:
      - ./web:/usr/src/app/web
      - ./web/public:/usr/src/app/web/public
      - ./web/node_modules:/usr/src/app/node_modules
    command: sh -c "npm rebuild node-sass && yarn dev"
